# Exported from Render on 2024-12-17T00:25:21Z
services:
- type: web
  name: django-projects
  runtime: python
  repo: https://github.com/TWOCHE/Django_DigitalVocabulary
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: ./build.sh
  startCommand: python -m gunicorn digitalvocabulary.asgi:application -k uvicorn.workers.UvicornWorker
version: "1"
