
databases:
  - name: digitalvocabularydb
    plan: free
    databaseName: digital_vocabulary
    user: tugce
    password: uyX3qiHun5RQs7mO1d1lGVx6vwwKnYyI
    host: dpg-cte071btq21c73fv886g-a.frankfurt-postgres.render.com
    port: 5432

services:
  - type: web
    plan: free
    name: digitalvocabulary
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn digitalvocabulary.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        value: "postgres://tugce:uyX3qiHun5RQs7mO1d1lGVx6vwwKnYyI@dpg-cte071btq21c73fv886g-a.frankfurt-postgres.render.com:5432/digital_vocabulary"
      - key: SECRET_KEY
        value: "5=vanz)0vd48wzqh_wq8774chblo+27g-7b44-5dcri+a$=hl2"
      - key: WEB_CONCURRENCY
        value: 4
