# Exported from Render on 2024-12-17T21:41:41Z
services:
- type: web
  name: PgHero-dpg-cte071btq21c73fv886g-a
  runtime: image
  image:
    url: docker.io/ankane/pghero:latest
  plan: free
  envVars:
  - key: WEB_CONCURRENCY
    sync: false
  - key: PGHERO_PASSWORD
    sync: false
  - key: PGHERO_USERNAME
    sync: false
  - key: DATABASE_URL
    sync: false
  region: frankfurt
version: "1"

        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
